# .github/workflows/publish.yml
#  https://jsr.io/docs/publishing-packages#publishing-from-github-actions

name: ci.deno.publish

on:
  push:
    branches:
      - phil-work

  workflow_run:
    workflows: ['ci.deno']
    types:
      - completed

jobs:
  check_conclusion:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Conclusion
        run: echo "Conclusion is ${{ github.event.workflow_run.conclusion }}"

  publish:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: cd code/deno/std && deno publish
      - run: cd code/deno/std.server && deno publish
