# https://docs.deno.com/deploy/manual/ci_github
name: ci.deno

on: [push]

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    env:
      DENO_SUBHOSTING_ACCESS_TOKEN: ${{ secrets.DENO_SUBHOSTING_ACCESS_TOKEN }}
      DENO_SUBHOSTING_DEPLOY_ORG_ID: ${{ secrets.DENO_SUBHOSTING_DEPLOY_ORG_ID }}
      PRIVY_APP_ID: ${{ secrets.PRIVY_APP_ID }}
      PRIVY_APP_SECRET: ${{ secrets.PRIVY_APP_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: DEBUG Secrets 🐷
        run: |
          # echo "Deploy token length: ${#DENO_SUBHOSTING_DEPLOY_ORG_ID}"
          echo "Org ID length: ${#DENO_SUBHOSTING_DEPLOY_ORG_ID}"

      - name: Version Info
        run: |
          deno --version
          deno task info

      - name: CI → type check (publish --dry-run)
        run: deno task dry

      - name: CI → tests
        run: deno task test
