name: ci.deno

on: [push]

jobs:
  build:
    name: deno.stats
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: '1.x'

      - name: Record start time
        id: start-time
        run: echo "::set-output name=time::$(date +%s%N)"

      - name: Deno Info
        run: |
          deno --version
          deno run --allow-env script.deno/info.ts

      - name: Record end time
        id: end-time
        run: echo "::set-output name=time::$(date +%s%N)"

      - name: Calculate elapsed time
        run: |
          ELAPSED_NANOSECONDS=$((${{ steps.end-time.outputs.time }} - ${{ steps.start-time.outputs.time }}))
          ELAPSED_MILLISECONDS=$(($ELAPSED_NANOSECONDS / 1000000))
          ELAPSED_SECONDS=$(($ELAPSED_MILLISECONDS / 1000))
          echo "Elapsed time: $ELAPSED_MILLISECONDS ms"
          echo "Elapsed time: $ELAPSED_SECONDS s"
        shell: bash
