# https://docs.deno.com/deploy/manual/ci_github
name: ci.deno

on: [push]

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    env:
      DENO_SYS_DEPLOY_ACCESS_TOKEN: ${{ secrets.DENO_SYS_DEPLOY_ACCESS_TOKEN }}
      DENO_SYS_DEPLOY_ORG_ID: ${{ secrets.DENO_SYS_DEPLOY_ORG_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Version Info
        run: |
          deno --version
          deno task info

      - name: CI → tests
        run: deno task test

      - name: CI → type check (publish --dry-run)
        run: deno task dry
