name: deno.ci.baseline

on: [push]

jobs:
  build:
    name: deno - baseline
    runs-on: ubuntu-latest

    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s%N)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Info
        run: |
          deno --version
          deno run --allow-env script.deno/info.ts

      - name: Set end time
        run: echo "END_TIME=$(date +%s%N)" >> $GITHUB_ENV

      - name: Calculate elapsed time
        run: |
          ELAPSED_MSECS=$((($END_TIME - $START_TIME)/1000000))
          ELAPSED_SECS=$(($ELAPSED_MSECS / 1000))
          echo "Elapsed time: $ELAPSED_MSECS msecs"
          echo "Elapsed time: $ELAPSED_SECS secs"
