name: ci.deno

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v1
        with:
          deno-version: 'v1.x'

      - name: Run TypeScript Script
        run: deno run script.deno/hello.ts
