name: ci.deno

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - run: |
          deno --version
          deno run script.deno/hello.ts
